language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=MetovaBase.xcodeproj
  - IOS_FRAMEWORK_SCHEME="MetovaBase-iOS"
  - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 7"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_install:
  - rvm use 2.3.0
install:
  - bundle install --without=documentation
script:
  - set -o pipefail
  - xcodebuild -version

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -c;
    else
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
after_success:
 - bundle binstub slather
 - bin/slather coverage --binary-basename MetovaBase
 - sleep 5 # https://github.com/travis-ci/travis-ci/issues/4725
